### PR TITLE
Allow people other than Elan to actually use this (also, how Andrea misinterprets stuff)

### PR DESCRIPTION
**Pull request by lucidstack**
*cough cough* 😅

### CODE REVIEW

**Comment by elan** [comment]
that’s not my ID! it’s a vestigial holdover from before multiuser and should just mean “owner” unless i’m confused.

**Comment by lucidstack** [comment]
Ooohh that's why I can only get it to work when I remove the condition. I use a shared user to play my music 🤦‍♂️

**Comment by elan** [comment]
ahhh, so just parameterize the user ID with the other parameters, presumably 😅

**Comment by lucidstack** [comment]
Ah, akes sense, thank you! I've parameterized the username, hope that's alright 😄

**Comment by elan** [comment]
Thanks @lucidstack!

**Pull request merged**
